spring.application.name=Kanbee_Back

# 1. Conexão
spring.datasource.url=jdbc:postgresql://db.svrzndofktibuvazcbft.supabase.co:5432/postgres
spring.datasource.username=postgres
spring.datasource.password=cPwOo6hgfnYKXrkA
spring.datasource.driver-class-name=org.postgresql.Driver

# 2. Configurações do Hibernate
spring.jpa.hibernate.ddl-auto=create-drop
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

# 3. Formatação
spring.output.ansi.enabled=ALWAYS